apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: <acrimage>
  newTag: "2.0.0"

bases:
- ../../base

namespace: sample-weatherapi-t4

configMapGenerator:
- name: pw-weatherapp-config
  files:
  - appsettings.json
- name: pw-weatherapp-env-file-vars
  envs:
  - server-vars.env

patches:
- target:
    kind: Ingress
    name: sample-deploy-prototype-ingress
  patch: |
    - op: replace
      path: /spec/rules/0/host
      value: <dns_name>
- target:
    group: <csi_driver>
    version: v1
    kind: SecretProviderClass
    name: azure-kvname-msi
  patch: |
    - op: replace
      path: /spec/parameters/userAssignedIdentityID
      value: <id>
    - op: replace
      path: /spec/parameters/keyvaultName
      value: <kv_value>
    - op: replace
      path: /spec/parameters/tenantId
      value: <tennatid>
- target:
    kind: Job
    name: presync-job
  patch: "- op: replace\n  path: /spec/template/spec/volumes/0/csi/volumeAttributes/secretProviderClass\n  value: \"azure-kvname-msi\"\n- op: add\n  path: \"/spec/template/spec/containers/0/env/-\"\n  value:\n    name: image_name\n    value: \"acrname.azurecr.io/dep-sample-linux-app-dotnet/prototypeweatherapi:2.0.0\"\n# Destination envitonment name to promote image above tags as per restartPolicy:\n# Tag below will be appened to the end of image \n- op: add\n  path: \"/spec/template/spec/containers/0/env/-\"\n  value:\n    name: dest_environment_name\n    value: \"test4\"\n## Branch reference in the dep-centralregistry-manager where the image promotion workflow resides.\n- op: add\n  path: \"/spec/template/spec/containers/0/env/-\"\n  value:\n    name: branch_ref\n    value: \"main\" #change this in case of testing workflow with other branch.\n# If this flag is enabled, will perform certain operations in the database to be mentioned in DataBaseName flag.\n- op: add\n  path: \"/spec/template/spec/containers/0/env/-\"\n  value:\n    name: DataBase_Ops_flag\n    value: \"true\"\n- op: add\n  path: \"/spec/template/spec/containers/0/env/-\"\n  value:\n    name: DataBaseName\n    value: \"test4-sql-database\"\n# Only if this is enabled the image promotion workflow will run \n- op: add\n  path: \"/spec/template/spec/containers/0/env/-\"\n  value:\n    name: Image_promotion_flag\n    value: \"true\"\n"

